------ Store procedure select ---------------------------
CREATE PROCEDURE SELECTPERSONAS
AS 
BEGIN
	SELECT * FROM PERSONAS
END
GO
----------------------------------------------------

------ Store procedure selectById ---------------------------
CREATE or alter PROCEDURE SELECTPERSONASBYID
@NOIDENTIFICACION VARCHAR(20)
AS 
BEGIN
	SELECT * FROM PERSONAS WHERE NOIDENTIFICACION = @NOIDENTIFICACION
END
GO
----------------------------------------------------

------ Store procedure insert PERSONAS  ---------------------------
CREATE or alter PROCEDURE INSERTPERSONAS(
@NOMBRES VARCHAR(150),
@APELLIDOS VARCHAR(150),
@NOIDENTIFICACION VARCHAR(20),
@EMAIL VARCHAR(50)  NULL,
@TIPOIDENTIFICACION VARCHAR(10),
@NOMBRESYAPELLIDOS VARCHAR(150)  NULL,
@IDENTIFICACIONYNOIDENTIFICACION VARCHAR(150) NULL
)
AS
BEGIN
	INSERT INTO PERSONAS (NOMBRES, APELLIDOS, NOIDENTIFICACION,EMAIL,TIPOIDENTIFICACION,FECHACREACION, NOMBRESYAPELLIDOS,IDENTIFICACIONYNOIDENTIFICACION)
	VALUES (@NOMBRES,@APELLIDOS,@NOIDENTIFICACION,@EMAIL, @TIPOIDENTIFICACION, GETDATE(),@NOMBRESYAPELLIDOS,@IDENTIFICACIONYNOIDENTIFICACION)
END
GO
----------------------------------------------------

------ Store procedure update PERSONAS  ------------------------------------------
CREATE or alter PROCEDURE UPDATEPERSONAS(
@IDENTIFICADOR INT,
@NOMBRES VARCHAR(150),
@APELLIDOS VARCHAR(150),
@EMAIL VARCHAR(50)  NULL,
@TIPOIDENTIFICACION VARCHAR(10),
@NOMBRESYAPELLIDOS VARCHAR(150) NULL,
@IDENTIFICACIONYNOIDENTIFICACION VARCHAR(150) NULL
)
AS
BEGIN

	UPDATE PERSONAS
	SET NOMBRES = @NOMBRES, APELLIDOS = @APELLIDOS, EMAIL = @EMAIL, TIPOIDENTIFICACION = @TIPOIDENTIFICACION,
	NOMBRESYAPELLIDOS = @NOMBRESYAPELLIDOS, IDENTIFICACIONYNOIDENTIFICACION = @IDENTIFICACIONYNOIDENTIFICACION
	WHERE  IDENTIFICADOR = @IDENTIFICADOR
END
GO
----------------------------------------------------------------------------------------------------
------ Store procedure delete GASTOS  ---------------------------
CREATE or alter PROCEDURE DELETEPERSONAS(
@IDENTIFICADOR INT,
@NOIDENTIFICACION VARCHAR(20)
)
AS
BEGIN

	DELETE PERSONAS 
	WHERE NOIDENTIFICACION = @NOIDENTIFICACION AND IDENTIFICADOR = @IDENTIFICADOR
END
GO
----------------------------------------------------