--drop table PERSONAS
CREATE TABLE PERSONAS(
IDENTIFICADOR INT IDENTITY  NOT NULL,
NOMBRES VARCHAR(150) NOT NULL,
APELLIDOS VARCHAR(150) NOT NULL,
NOIDENTIFICACION VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50)  NULL,
TIPOIDENTIFICACION VARCHAR(10) NOT NULL,
FECHACREACION DATETIME NULL,
NOMBRESYAPELLIDOS VARCHAR(150) NOT NULL,
IDENTIFICACIONYNOIDENTIFICACION VARCHAR(150) NOT NULL
)

ALTER TABLE PERSONAS
ADD CONSTRAINT PERSONASIDENTIFICADOR
PRIMARY KEY CLUSTERED (IDENTIFICADOR)

select * from PERSONAS

--sp_help usuarios

---select * from usuarios



